https://www.perplexity.ai/search/f834ba4a-c32d-48c7-bfc3-36ef4d2b6d11

In [ ]:
#list
scores:list = [10, 20, 30, 40, 50]
scores:list = list(range(10,60,10))

# scores1:list = list()
# for score in scores:
#     score += 5
#     scores1.append(score)
scores1 = [score+5 for score in scores]
scores1

[15, 25, 35, 45, 55]

In [ ]:
#numpy
import numpy as np

array = np.array([10, 20, 30, 40, 50])
type(array)
array1 = array + 5
array1

array([15, 25, 35, 45, 55])

In [11]:
import numpy as np

#建立一個1D陣列
a = np.array([1, 2, 3])
print(a)

#建立一個2*3的全0矩陣
b = np.zeros((2, 3))
print(b)

#建立一個3*3的單位矩陣
c = np.eye(3)
print(c)

#陣列的加法
d = a + [4, 5, 6]
print(d)

[1 2 3]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[5 7 9]
