https://www.perplexity.ai/search/045ecda7-23bf-4d76-9155-fcb886e2425e

In [1]:
import numpy as np
np.random.random()
np.random.random(3)
np.random.random(size=3)
np.random.random((3, 4))
np.random.random(size=(3,4))

array([[0.27187159, 0.72388568, 0.87144523, 0.24285039],
       [0.20640018, 0.6917684 , 0.63298145, 0.92279635],
       [0.27925093, 0.74917368, 0.59209087, 0.30044247]])

In [2]:
from numpy.random import normal 

normal_value = normal(size=(3, 4))
#ndarray常用的實體屬性
type(normal_value)
normal_value.ndim
normal_value.size
normal_value.shape
normal_value.dtype

dtype('float64')

In [3]:
#ndarray,陣列運算
normal_value * 10

array([[ 13.02312309,   3.44983994,  -0.89860937,  -9.92393404],
       [-17.72779745,   0.23452631,  10.64169452,   5.93931491],
       [  4.5314259 , -13.26793473,   4.23532815,   0.93994005]])

In [4]:
#ndarray,的統計
normal_value.sum()
normal_value.sum(axis=0)
normal_value.sum(axis=1)

array([ 0.56504196, -0.09122617, -0.35612406])